<a href="https://colab.research.google.com/github/vishant016/140_VISHANT/blob/main/LAB1/LAB1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**
1. Create Two numpy array of size 3 X 2 and 2 X 3
2. Randomly Initalize that array
3. Perform matrix multiplication
4. Perform elementwise matrix multiplication
5. Find mean of first matrix
6. Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version 
**

In [10]:
import numpy as np
import random
A = np.arange(6).reshape(3,2)
B = np.arange(0,6).reshape(2,3)
print(A)

print(B)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [17]:
A=np.empty([3,2] ,dtype=int)
B=np.empty([2,3] ,dtype=int)
print(A)
print(B)

[[0 1]
 [2 3]
 [4 5]]
[[94028575124720              0              0]
 [             0              0              0]]


In [11]:
np.dot(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [21]:
np.mean(A)

2.5

In [23]:
import pandas as pd
mtcar = pd.read_csv('/content/drive/MyDrive/ML/Dataset/mtcars.csv')
del mtcar['model']
meancenter=mtcar.apply(lambda x: x-x.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
