<a href="https://colab.research.google.com/github/vishant016/140_VISHANT/blob/main/LAB5/2_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [3]:
# Imports
import torch.nn as nn

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [13]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [11]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [14]:
# Define dataset
dataset = torch.utils.data.TensorDataset(inputs,targets)


In [15]:
# Define data loader
dataloader = torch.utils.data.DataLoader(dataset,batch_size=5)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [16]:
# Define model
model = nn.Linear(inputs.shape[1],targets.shape[1])
model.parameters()

<generator object Module.parameters at 0x7fb6545a6450>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [17]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)


### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [18]:
# Import nn.functional
import torch.nn.functional as F

In [19]:
# Define loss function
loss_fn = F.mse_loss

In [20]:
#loss = loss_fn(? , ?)
#print(loss)

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [21]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in dataloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
       print('Training loss: ', loss_fn(model(inputs), targets))

In [22]:

# Train the model for 100 epochs
fit(120 , model , loss_fn, optimizer)



Training loss:  tensor(3833.4336, grad_fn=<MseLossBackward>)
Training loss:  tensor(1143.2247, grad_fn=<MseLossBackward>)
Training loss:  tensor(426.8425, grad_fn=<MseLossBackward>)
Training loss:  tensor(211.9994, grad_fn=<MseLossBackward>)
Training loss:  tensor(132.3152, grad_fn=<MseLossBackward>)
Training loss:  tensor(94.0960, grad_fn=<MseLossBackward>)
Training loss:  tensor(71.7060, grad_fn=<MseLossBackward>)
Training loss:  tensor(57.0472, grad_fn=<MseLossBackward>)
Training loss:  tensor(46.9055, grad_fn=<MseLossBackward>)
Training loss:  tensor(39.6613, grad_fn=<MseLossBackward>)
Training loss:  tensor(34.3548, grad_fn=<MseLossBackward>)
Training loss:  tensor(30.3695, grad_fn=<MseLossBackward>)
Training loss:  tensor(27.2959, grad_fn=<MseLossBackward>)
Training loss:  tensor(24.8584, grad_fn=<MseLossBackward>)
Training loss:  tensor(22.8701, grad_fn=<MseLossBackward>)
Training loss:  tensor(21.2038, grad_fn=<MseLossBackward>)
Training loss:  tensor(19.7727, grad_fn=<MseLossB

In [23]:
# Generate predictions
#preds = model(?)
#preds
preds = model(inputs)
preds

tensor([[ 57.2774,  70.3090],
        [ 82.0033, 100.4964],
        [118.9774, 133.3532],
        [ 21.1535,  37.1277],
        [101.6362, 118.7437],
        [ 57.2774,  70.3090],
        [ 82.0033, 100.4964],
        [118.9774, 133.3532],
        [ 21.1535,  37.1277],
        [101.6362, 118.7437],
        [ 57.2774,  70.3090],
        [ 82.0033, 100.4964],
        [118.9774, 133.3532],
        [ 21.1535,  37.1277],
        [101.6362, 118.7437]], grad_fn=<AddmmBackward>)

In [24]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [25]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.5,random_state=140)

In [27]:
model.fit(X_train,Y_train)
predictions = model.predict(X_test)
predictions

array([[ 98.71938 , 119.30003 ],
       [119.      , 133.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ],
       [119.      , 133.      ],
       [ 56.000008,  70.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ]], dtype=float32)

In [28]:
Y_test

tensor([[103., 119.],
        [119., 133.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [ 81., 101.]])

In [29]:
from sklearn.metrics import mean_squared_error

print(mean_squared_error(Y_test,predictions))

3.4525688


In [45]:
import tensorflow as tf

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float64')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')



In [46]:
model = tf.keras.Sequential()
model.compile(loss="mean_squared_error")

In [47]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [48]:


v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print()
print(r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.78507783, 0.90220197],
       [0.69555327, 0.15370827],
       [0.73759223, 0.11453492]])>

<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([3.36472942, 0.00533027])>


In [49]:
def model(s):
    return s @ v + r

In [50]:
prediction = model(inputs)
prediction

<tf.Tensor: shape=(15, 2), dtype=float64, numpy=
array([[138.99394601,  81.08952922],
       [183.22140242, 102.96227155],
       [207.65098809, 105.73683439],
       [140.64237135, 102.8771783 ],
       [175.93966961,  85.03070397],
       [138.99394601,  81.08952922],
       [183.22140242, 102.96227155],
       [207.65098809, 105.73683439],
       [140.64237135, 102.8771783 ],
       [175.93966961,  85.03070397],
       [138.99394601,  81.08952922],
       [183.22140242, 102.96227155],
       [207.65098809, 105.73683439],
       [140.64237135, 102.8771783 ],
       [175.93966961,  85.03070397]])>

In [51]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(5095.623962208768, shape=(), dtype=float64)


In [52]:
epochs = 25
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f"Epoch: {epoch_count} \n Loss: {current_loss.numpy()} \n\n")

Epoch: 0 
 Loss: 5095.623962208768 


Epoch: 1 
 Loss: 3431.9944122347597 


Epoch: 2 
 Loss: 2362.330724020395 


Epoch: 3 
 Loss: 1667.7761649810186 


Epoch: 4 
 Loss: 1210.9826217407488 


Epoch: 5 
 Loss: 905.6464572422625 


Epoch: 6 
 Loss: 697.4437628483136 


Epoch: 7 
 Loss: 552.0978237633337 


Epoch: 8 
 Loss: 447.90916823159955 


Epoch: 9 
 Loss: 371.0780051602416 


Epoch: 10 
 Loss: 312.7741073581277 


Epoch: 11 
 Loss: 267.30036229713744 


Epoch: 12 
 Loss: 230.94093148083937 


Epoch: 13 
 Loss: 201.23806195059055 


Epoch: 14 
 Loss: 176.53737997164274 


Epoch: 15 
 Loss: 155.70142607223104 


Epoch: 16 
 Loss: 137.9286868334753 


Epoch: 17 
 Loss: 122.63884052824379 


Epoch: 18 
 Loss: 109.39961494855093 


Epoch: 19 
 Loss: 97.8798435293155 


Epoch: 20 
 Loss: 87.81905655207817 


Epoch: 21 
 Loss: 79.00754430783041 


Epoch: 22 
 Loss: 71.273083493172 


Epoch: 23 
 Loss: 64.47193037564624 


Epoch: 24 
 Loss: 58.48256945479234 




In [53]:
model(inputs)

<tf.Tensor: shape=(15, 2), dtype=float64, numpy=
array([[ 59.15533018,  72.9252873 ],
       [ 82.00180549,  98.24003798],
       [114.69082471, 134.29264991],
       [ 30.24652018,  51.78793082],
       [ 96.969524  , 106.28844511],
       [ 59.15533018,  72.9252873 ],
       [ 82.00180549,  98.24003798],
       [114.69082471, 134.29264991],
       [ 30.24652018,  51.78793082],
       [ 96.969524  , 106.28844511],
       [ 59.15533018,  72.9252873 ],
       [ 82.00180549,  98.24003798],
       [114.69082471, 134.29264991],
       [ 30.24652018,  51.78793082],
       [ 96.969524  , 106.28844511]])>