<a href="https://colab.research.google.com/github/vishant016/140_VISHANT/blob/main/LAB5/2_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = torch.utils.data.TensorDataset(inputs,targets)


In [7]:
# Define data loader
dataloader = torch.utils.data.DataLoader(dataset,batch_size=5)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
model = nn.Linear(inputs.shape[1],targets.shape[1])
model.parameters()

<generator object Module.parameters at 0x7f08f1a37ed0>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)


### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [11]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
#loss = loss_fn(? , ?)
#print(loss)

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [22]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in dataloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
       print('Training loss: ', loss_fn(model(inputs), targets))

In [23]:

# Train the model for 100 epochs
fit(120 , model , loss_fn, optimizer)



Training loss:  tensor(1220.2104, grad_fn=<MseLossBackward>)
Training loss:  tensor(555.8185, grad_fn=<MseLossBackward>)
Training loss:  tensor(314.6598, grad_fn=<MseLossBackward>)
Training loss:  tensor(202.3452, grad_fn=<MseLossBackward>)
Training loss:  tensor(138.6223, grad_fn=<MseLossBackward>)
Training loss:  tensor(98.3211, grad_fn=<MseLossBackward>)
Training loss:  tensor(71.5500, grad_fn=<MseLossBackward>)
Training loss:  tensor(53.3683, grad_fn=<MseLossBackward>)
Training loss:  tensor(40.8645, grad_fn=<MseLossBackward>)
Training loss:  tensor(32.1759, grad_fn=<MseLossBackward>)
Training loss:  tensor(26.0695, grad_fn=<MseLossBackward>)
Training loss:  tensor(21.7180, grad_fn=<MseLossBackward>)
Training loss:  tensor(18.5637, grad_fn=<MseLossBackward>)
Training loss:  tensor(16.2294, grad_fn=<MseLossBackward>)
Training loss:  tensor(14.4601, grad_fn=<MseLossBackward>)
Training loss:  tensor(13.0828, grad_fn=<MseLossBackward>)
Training loss:  tensor(11.9803, grad_fn=<MseLossBa

In [24]:
# Generate predictions
#preds = model(?)
#preds
preds = model(inputs)
preds

tensor([[ 57.2301,  70.2502],
        [ 82.1557, 100.5431],
        [118.7064, 133.3408],
        [ 21.0801,  37.1288],
        [101.9070, 118.7562],
        [ 57.2301,  70.2502],
        [ 82.1557, 100.5431],
        [118.7064, 133.3408],
        [ 21.0801,  37.1288],
        [101.9070, 118.7562],
        [ 57.2301,  70.2502],
        [ 82.1557, 100.5431],
        [118.7064, 133.3408],
        [ 21.0801,  37.1288],
        [101.9070, 118.7562]], grad_fn=<AddmmBackward>)

In [25]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [26]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [27]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.5,random_state=140)

In [28]:
model.fit(X_train,Y_train)
predictions = model.predict(X_test)
predictions

array([[ 98.71938 , 119.30003 ],
       [119.      , 133.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ],
       [119.      , 133.      ],
       [ 56.000008,  70.      ],
       [ 98.71938 , 119.30003 ],
       [ 81.      , 101.      ]], dtype=float32)

In [29]:
Y_test

tensor([[103., 119.],
        [119., 133.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [ 81., 101.]])

In [30]:
from sklearn.metrics import mean_squared_error

print(mean_squared_error(Y_test,predictions))

3.4525688


In [31]:
import tensorflow as tf

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

X_train,X_test,Y_train,Y_test = train_test_split(inputs,targets,test_size=0.5,random_state=140)

In [33]:
model = tf.keras.Sequential()
model.compile(loss="mean_squared_error")