<a href="https://colab.research.google.com/github/vishant016/140_VISHANT/blob/main/LAB3/3_NB_Classifier_Iris_3Classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
        
#Load dataset
iris = datasets.load_iris() 

In [4]:
# print the names of the 13 features
print("Features: ", iris.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)                                                                            

# print data(feature)shape
iris.data.shape  

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [6]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
                        iris.target, test_size = 0.30, random_state = 10) 

In [7]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [8]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [9]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


**Exercise:**

**1) 1<=Rollnumber<=25:**
  #Task 1: Try the algo on Dataset1 - OneHotEncoding of features: and Train test Division 70%-30%

  #Task 2: Apply algorithm on digits dataset - LabelEncoding of features: and Train test Division 80%-20%

**2) 26<=Rollnumber<=50:**
  #Task 1: Try the algo on Dataset1 - LabelEncoding of features: and Train test Division 80%-20%

   #Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 60%-40%

**3) 51<=Rollnumber<=75:**
  #Task 1: Try the algo on Dataset2 - LabelEncoding of features: and Train test Division 90%-10%

  #Task 2: Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division 65%-35%

**4) 76<=Rollnumber<=100:**
  #Task 1: Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%
  #Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%

**5) 101<=Rollnumber<=125:**
  #Task 1: Try the algo on Dataset3 - OneHotEncoding of features:and Train test Division 85%-15%
 #Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 66%-34%

**6) 126<=Rollnumber + All with No RollNumbers:**
  #Task 1: Try the algo on Dataset3 - LabelEncoding of features:and Train test Division 95%-5%
  
 #Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%



**Instruction for Task-1 & 2:**

i) Set Random state of model equals to your roll number (or last 2 digit of your id -if you don't have roll number)


**Questions: For Task - 1**

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

(3) Accuracy , precision and recall of both Models?


In [10]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [11]:
import pandas as pd
import numpy as np

In [13]:
data=pd.read_csv('/content/drive/MyDrive/ML/Dataset3.csv');
print(data)

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
le=LabelEncoder()
for i in range(0,3):
    data.iloc[:,[i]]=le.fit_transform(data.iloc[:,[i]])


In [23]:
data

Outlook  Temp  Wind  Humidity  Class
0         1     1     0         1      0
1         1     1     1         2      0
2         0     1     0         1      1
3         1     2     0         1      1
4         2     0     0         1      1
5         0     0     1         0      0
6         0     0     1         1      1
7         1     2     0         1      0
8         0     0     0         0      1
9         2     2     0         2      1
10        1     0     1         2      0
11        0     2     1         0      1
12        0     1     0         1      1
13        2     2     1         1      0

In [25]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values
print(X.shape)
print(Y.shape)

(14, 4)
(14,)


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,
                        Y, test_size = 0.05, random_state = 140)

In [28]:
nb=GaussianNB()
nb.fit(X_train,Y_train)
nb.predict([[1,2,0,1],[2,0,1,2]])  #Rainy,Mild,False,Normal  Sunny,Cool,True,High

array([1, 1])

In [29]:
predicted_data=nb.predict(X_test)
predicted_data

array([1])

In [37]:
print("Accuracy:",metrics.accuracy_score(Y_test, predicted_data))
confusion_matrix(Y_test, predicted_data,labels=[0,1])

Accuracy: 0.0


array([[0, 1],
       [0, 0]])

In [35]:
precision = precision_score(Y_test, predicted_data, average=None)
recall = recall_score(Y_test, predicted_data, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 0.]
recall: [0. 0.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
