<a href="https://colab.research.google.com/github/vishant016/140_VISHANT/blob/main/LAB6/0_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [ ]:


# reading the csv file, del 2 columns from the file, checking first few rows of the file

data = pd.read_csv('/content/drive/MyDrive/ML/Dataset/BuyComputer.csv')

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:


#Declare label as last column in the source file
Y = data.iloc[:,-1]



In [ ]:
#Declaring X as all columns excluding last
X = data.iloc[:,:2]

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=140,test_size=0.5)

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [ ]:
entries = len(X_train[:,0])
entries

200

In [ ]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [ ]:
# Sigmoid function
def sigmoid(z):
  sig = 1/(1+np.exp(-z))
  return sig

In [ ]:
def predict(inputs):
    return np.matmul(inputs,w)+b
def h(inputs):
    return sigmoid(predict(inputs))

In [ ]:
#Loss function
def loss_func(y,a):
    J = 0
    for i in range(0,len(y)):
        J += y[i]*np.log(h(X_train[i]))+(1-y[i])*np.log(1-h(X_train[i]))
    return -J
def gradient_descend(lr):
    tmp = h(X_train)
    for i in range(0,len_x):
        w[i]-=lr*np.sum((tmp.flatten()-y_train)*X_train[:,i])
    global b
    b-=lr*np.sum(tmp.flatten()-y_train)       

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

In [ ]:
#Repeating the process 3000 times
for i in range(0,3000):
    gradient_descend(lr=alpha)

In [ ]:
#Print weight
w

[3.855814855010906, 1.7192264914639654]

In [ ]:
#print bias
b

-1.0687789730244739

In [ ]:
#predicting the label
y_ = h(X_test)
y_ = y_.flatten()
y_predicted = (y_ >= .5).astype(int)
y_predicted

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0])

In [ ]:
#print actual and predicted values in a table
y_test

306    0
142    0
364    1
8      0
253    1
      ..
235    1
169    0
262    1
348    0
158    0
Name: Purchased, Length: 200, dtype: int64

In [ ]:
# Calculating accuracy of prediction
np.sum(y_predicted == y_test)/len(X_test)

0.83

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predicted)

array([[100,  23],
       [ 11,  66]])

#Using sklearn LogisticRegression model

In [ ]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_predicted = LR.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_predicted)

array([[111,  12],
       [ 25,  52]])

**Exercise:**

Try logistic regression on BuyComputer dataset and set Random state=Your_RollNumber (last 3 digit of ID, incase if you don't have ID)